// Searchable board-icon catalog: emoji tagged with names + keywords so the
// picker's search finds them ("timer" → ⏱ ⏲ ⏰ ⌛ …). Kept dependency-free;
// letters & numbers render as typographic tiles from LETTER_ICONS.
export interface IconEntry {
  e: string; // the emoji
  k: string; // space-separated name + keywords (lowercase)
}

export const ICON_CATALOG: IconEntry[] = [
  // time
  { e: '⏱️', k: 'stopwatch timer time speed track' },
  { e: '⏲️', k: 'timer clock countdown time' },
  { e: '⏰', k: 'alarm clock timer morning wake time' },
  { e: '🕐', k: 'clock time hour watch schedule' },
  { e: '⌛', k: 'hourglass timer sand time wait deadline' },
  { e: '⏳', k: 'hourglass timer sand time running deadline' },
  { e: '📅', k: 'calendar date schedule plan month' },
  { e: '🗓️', k: 'calendar schedule planner date' },
  // work & docs
  { e: '📝', k: 'memo note write pencil draft' },
  { e: '📄', k: 'page document file paper' },
  { e: '📋', k: 'clipboard tasks checklist plan' },
  { e: '📚', k: 'books library read study research' },
  { e: '📖', k: 'book open read story novel' },
  { e: '✏️', k: 'pencil write edit draw sketch' },
  { e: '🖋️', k: 'pen fountain write signature ink' },
  { e: '📌', k: 'pin location mark important' },
  { e: '📎', k: 'paperclip attach file' },
  { e: '🗂️', k: 'folders organize files archive dividers' },
  { e: '📁', k: 'folder files directory' },
  { e: '💼', k: 'briefcase work business job office' },
  { e: '🗃️', k: 'card file box archive storage' },
  { e: '📊', k: 'chart bar graph analytics data stats' },
  { e: '📈', k: 'chart up growth trending increase stats' },
  { e: '📉', k: 'chart down decrease loss stats' },
  { e: '🧮', k: 'abacus math calculate numbers' },
  // creative
  { e: '🎨', k: 'art palette paint design color creative' },
  { e: '🖌️', k: 'paintbrush paint art design' },
  { e: '🖍️', k: 'crayon draw color art' },
  { e: '✂️', k: 'scissors cut craft' },
  { e: '📷', k: 'camera photo picture photography' },
  { e: '📸', k: 'camera flash photo picture selfie' },
  { e: '🎬', k: 'clapper film movie video cinema director scene' },
  { e: '🎥', k: 'movie camera film video record cinema' },
  { e: '📽️', k: 'film projector movie cinema video' },
  { e: '🎞️', k: 'film frames movie strip cinema video' },
  { e: '📹', k: 'video camera record camcorder' },
  { e: '🎭', k: 'theater masks drama performing arts acting' },
  { e: '🎪', k: 'circus tent carnival event show' },
  { e: '🎵', k: 'music note song melody audio' },
  { e: '🎶', k: 'music notes song melody audio' },
  { e: '🎸', k: 'guitar music rock instrument band' },
  { e: '🎹', k: 'piano keyboard music instrument' },
  { e: '🎧', k: 'headphones music audio listen podcast' },
  { e: '🎤', k: 'microphone sing karaoke voice record podcast' },
  { e: '🎼', k: 'musical score sheet music compose' },
  { e: '✍️', k: 'writing hand write author script' },
  // tech
  { e: '💻', k: 'laptop computer code work tech dev' },
  { e: '🖥️', k: 'desktop computer monitor screen tech' },
  { e: '⌨️', k: 'keyboard typing code tech' },
  { e: '🖱️', k: 'mouse computer click tech' },
  { e: '📱', k: 'phone mobile smartphone app' },
  { e: '⚙️', k: 'gear settings config engineering mechanics' },
  { e: '🔧', k: 'wrench tool fix repair maintenance' },
  { e: '🔨', k: 'hammer build tool construction' },
  { e: '🛠️', k: 'tools hammer wrench build workshop' },
  { e: '🔩', k: 'nut bolt screw hardware engineering' },
  { e: '🧲', k: 'magnet attract physics science' },
  { e: '🔋', k: 'battery power energy charge' },
  { e: '💡', k: 'idea lightbulb inspiration bright think innovation' },
  { e: '🔦', k: 'flashlight torch light search' },
  { e: '🤖', k: 'robot ai bot machine automation' },
  { e: '🧠', k: 'brain mind think smart ideas psychology memory' },
  { e: '🔌', k: 'plug electric power connect' },
  // science & study
  { e: '🔬', k: 'microscope science lab research biology' },
  { e: '🧪', k: 'test tube science lab chemistry experiment' },
  { e: '🧬', k: 'dna genetics science biology' },
  { e: '🔭', k: 'telescope astronomy space stars science' },
  { e: '🎓', k: 'graduation cap education school university degree study' },
  { e: '🏫', k: 'school education building study' },
  { e: '🌡️', k: 'thermometer temperature weather health' },
  // travel & places
  { e: '✈️', k: 'airplane travel flight trip vacation' },
  { e: '🚗', k: 'car drive vehicle road trip' },
  { e: '🚀', k: 'rocket launch space startup fast ship' },
  { e: '🚢', k: 'ship boat cruise sea travel' },
  { e: '⛵', k: 'sailboat sailing sea boat' },
  { e: '🚲', k: 'bicycle bike cycling exercise' },
  { e: '🗺️', k: 'map travel world navigation location' },
  { e: '🧭', k: 'compass navigation direction explore adventure' },
  { e: '🏠', k: 'house home building living' },
  { e: '🏢', k: 'office building company work city' },
  { e: '🏗️', k: 'construction crane building site project' },
  { e: '🏔️', k: 'mountain snow peak hiking adventure nature' },
  { e: '🏖️', k: 'beach vacation umbrella sand summer holiday' },
  { e: '🕌', k: 'mosque islam masjid prayer religion' },
  { e: '🕋', k: 'kaaba mecca hajj islam pilgrimage' },
  { e: '⛺', k: 'tent camping outdoor adventure' },
  { e: '🌍', k: 'globe world earth global international planet' },
  { e: '🗽', k: 'statue liberty new york landmark travel' },
  { e: '🗼', k: 'tower tokyo paris landmark travel' },
  // nature
  { e: '🌱', k: 'seedling plant grow sprout garden nature green' },
  { e: '🌳', k: 'tree nature forest green park' },
  { e: '🌸', k: 'blossom flower spring cherry pink nature' },
  { e: '🌵', k: 'cactus desert plant nature' },
  { e: '🌊', k: 'wave ocean sea water surf nature' },
  { e: '☀️', k: 'sun sunny weather bright summer day' },
  { e: '🌙', k: 'moon night crescent sleep ramadan' },
  { e: '⭐', k: 'star favorite rating shine best' },
  { e: '🌟', k: 'star glowing shine sparkle special' },
  { e: '⚡', k: 'lightning bolt fast energy power electric flash' },
  { e: '🔥', k: 'fire hot flame trending burn lit' },
  { e: '❄️', k: 'snowflake winter cold snow ice' },
  { e: '🌈', k: 'rainbow color pride weather hope' },
  { e: '☁️', k: 'cloud weather sky storage' },
  { e: '🌧️', k: 'rain cloud weather storm' },
  { e: '🍂', k: 'autumn fall leaves nature season' },
  // animals
  { e: '🐱', k: 'cat kitten pet animal' },
  { e: '🐶', k: 'dog puppy pet animal' },
  { e: '🦅', k: 'eagle bird falcon hunting animal' },
  { e: '🐪', k: 'camel desert animal arabia' },
  { e: '🐎', k: 'horse riding animal speed' },
  { e: '🦋', k: 'butterfly nature transform beauty' },
  { e: '🐝', k: 'bee honey busy work insect' },
  { e: '🐟', k: 'fish sea animal fishing aquarium' },
  // food
  { e: '🍽️', k: 'plate fork knife dinner restaurant meal food' },
  { e: '☕', k: 'coffee cup drink cafe hot espresso' },
  { e: '🍵', k: 'tea cup drink hot green' },
  { e: '🍕', k: 'pizza food italian slice' },
  { e: '🍔', k: 'burger food fast hamburger' },
  { e: '🍰', k: 'cake dessert sweet birthday slice' },
  { e: '🍎', k: 'apple fruit red healthy food' },
  { e: '🥗', k: 'salad healthy food green diet' },
  { e: '🍳', k: 'cooking egg pan breakfast kitchen recipe' },
  { e: '🧁', k: 'cupcake dessert sweet baking' },
  { e: '🍇', k: 'grapes fruit food wine' },
  { e: '🥘', k: 'paella pan food cooking dish recipe' },
  // activities & sports
  { e: '⚽', k: 'soccer football sport ball game' },
  { e: '🏀', k: 'basketball sport ball game' },
  { e: '🎾', k: 'tennis sport ball game' },
  { e: '🏊', k: 'swimming pool sport water exercise' },
  { e: '🏋️', k: 'weightlifting gym exercise fitness strength workout' },
  { e: '🧘', k: 'yoga meditation zen calm wellness mindfulness' },
  { e: '🏃', k: 'running exercise sprint marathon fitness' },
  { e: '🎮', k: 'game controller video gaming play' },
  { e: '🎲', k: 'dice game random chance board' },
  { e: '🧩', k: 'puzzle piece jigsaw problem solving' },
  { e: '♟️', k: 'chess pawn strategy game' },
  { e: '🎣', k: 'fishing rod hobby sea' },
  { e: '⛳', k: 'golf flag hole sport' },
  // celebration & social
  { e: '🎉', k: 'party popper celebrate confetti birthday event tada' },
  { e: '🎊', k: 'confetti ball celebrate party event' },
  { e: '🎁', k: 'gift present birthday surprise box' },
  { e: '🎂', k: 'birthday cake celebrate party' },
  { e: '💍', k: 'ring wedding engagement marriage jewelry' },
  { e: '👶', k: 'baby child newborn family' },
  { e: '👥', k: 'people team group community users' },
  { e: '💬', k: 'speech bubble chat talk message comment' },
  { e: '❤️', k: 'heart love red favorite like' },
  { e: '💕', k: 'hearts love romance couple' },
  { e: '🤝', k: 'handshake deal agreement partnership meeting' },
  // money & goals
  { e: '💰', k: 'money bag cash budget finance savings' },
  { e: '💳', k: 'credit card payment money finance' },
  { e: '🪙', k: 'coin money gold finance crypto' },
  { e: '🏦', k: 'bank money finance building' },
  { e: '🛒', k: 'shopping cart groceries buy store' },
  { e: '🛍️', k: 'shopping bags buy store retail' },
  { e: '🎯', k: 'target dart goal aim focus bullseye objective' },
  { e: '🏆', k: 'trophy winner champion award prize achievement' },
  { e: '🥇', k: 'gold medal first winner achievement' },
  { e: '🔑', k: 'key unlock access password secret' },
  { e: '🔒', k: 'lock secure private password protected' },
  { e: '🛡️', k: 'shield security protect safety defense' },
  { e: '⚖️', k: 'scales balance law justice legal' },
  // symbols & flags
  { e: '✅', k: 'check mark done complete yes approved' },
  { e: '❌', k: 'cross x no wrong cancel rejected' },
  { e: '❓', k: 'question mark help unknown ask' },
  { e: '❗', k: 'exclamation important warning alert' },
  { e: '⚠️', k: 'warning caution alert danger attention' },
  { e: '🚩', k: 'flag red marker milestone warning' },
  { e: '🏁', k: 'checkered flag finish race complete done' },
  { e: '➕', k: 'plus add new create' },
  { e: '♾️', k: 'infinity forever endless loop' },
  { e: '☪️', k: 'star crescent islam religion' },
  { e: '📢', k: 'megaphone announce loud marketing broadcast' },
  { e: '🔔', k: 'bell notification alert reminder ring' },
  { e: '🗳️', k: 'ballot vote election box' },
  { e: '💤', k: 'sleep zzz rest nap' },
  { e: '🩺', k: 'stethoscope doctor health medical' },
  { e: '💊', k: 'pill medicine health pharmacy drug' },
  { e: '🧳', k: 'luggage suitcase travel trip packing' },
  { e: '🪴', k: 'potted plant home decor garden' },
  { e: '🧵', k: 'thread sewing craft needle' },
  { e: '🧶', k: 'yarn knitting craft wool' },
  { e: '👗', k: 'dress fashion clothes style' },
  { e: '👔', k: 'tie shirt formal business fashion' },
  { e: '👟', k: 'sneaker shoe running fashion' },
  { e: '👑', k: 'crown king queen royal vip' },
  { e: '💎', k: 'gem diamond jewel precious value' },
];

// Letters & numbers tab: rendered as typographic tiles.
export const LETTER_ICONS: string[] = [
  ...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  ...'0123456789'.split(''),
  '&', '#', '@', '!', '?', '★', '№',
];

// searchIcons filters the catalog by all query terms (any keyword prefix).
export function searchIcons(query: string): IconEntry[] {
  const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return ICON_CATALOG;
  return ICON_CATALOG.filter((entry) => terms.every((t) => entry.k.includes(t)));
}

// isLetterIcon: single typographic character (renders as a letter tile).
export function isLetterIcon(icon: string): boolean {
  return icon.length <= 2 && /^[A-Z0-9&#@!?★№]{1,2}$/.test(icon);
}
